# Generated by Django 5.1.15 on 2026-04-01 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar_x',
            field=models.FloatField(default=50.0),
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar_y',
            field=models.FloatField(default=50.0),
        ),
    ]
