# Generated by Django 5.1.15 on 2026-04-01 04:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_profile_last_seen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompatibilityScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('interests', 'Interests Alignment'), ('communication', 'Communication Style'), ('values', 'Values Match'), ('lifestyle', 'Lifestyle Sync')], max_length=20)),
                ('ai_score', models.FloatField(default=50.0)),
                ('ai_updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compat_scores', to='api.profile')),
            ],
            options={
                'unique_together': {('profile', 'category')},
            },
        ),
        migrations.CreateModel(
            name='CompatibilityVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='api.compatibilityscore')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compat_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('score', 'voter')},
            },
        ),
    ]
